# Generated by Django 2.1 on 2020-01-17 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogHandlerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.TextField()),
                ('context', models.TextField()),
                ('level', models.TextField()),
                ('message', models.TextField()),
            ],
        ),
    ]
